server.port: 9000

spring:
  application:
    name: llm-usage-tracker-api
  datasource:
    url: jdbc:mariadb://localhost:3399/llm-usage-tracker-db?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
